indexing-settings:
  input:
#    - url: https://ipfran.ru
#      name: ipfran
#    - url: https://skillbox.ru
#      name: Skillbox
    - url: https://volochek.life
      name: volochek
#    - url: http://radiomv.ru
#      name: radio
    - url: https://dimonvideo.ru
      name: dimonvideo
#    - url: https://nikoartgallery.com
#      name: nikoartgallery
#    - url:  https://et-cetera.ru/mobile
#      name: et-cetera.ru
#    - url:  https://lutherancathedral.ru
#      name: lutherancathedral
#    - url:  https://dombulgakova.ru/
#      name: dombulgakova
#    - url:  https://svetlovka.ru
#      name: svetlovka


spring:
  datasource:
    url: jdbc:mysql://localhost:3307/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true